# Generated by Django 2.0.8 on 2018-08-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carro_modelo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Condutores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condutor_nome', models.CharField(default='null', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Viagens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viagens_kilometros', models.DecimalField(decimal_places=2, max_digits=5)),
                ('viagens_data', models.DateField()),
                ('viagens_destino', models.CharField(default='null', max_length=200)),
                ('viagens_carro', models.ForeignKey(on_delete='on_delete.CASCADE', to='carcontrol.Carro')),
                ('viagens_condutor', models.ForeignKey(on_delete='on_delete.CASCADE', related_name='condutores', to='carcontrol.Condutores')),
            ],
        ),
    ]
