# Generated by Django 2.1 on 2018-09-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPF_Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=300)),
                ('complemento', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disponibildiade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pacote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pacote', models.CharField(max_length=200)),
                ('desc_pacote', models.CharField(max_length=400)),
                ('valor_pacote', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_pacote_entrada', models.DateField()),
                ('data_pacote_saida', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField()),
                ('data_saida', models.DateField()),
                ('situacao', models.BooleanField(default=False)),
                ('reserva_cliente', models.ForeignKey(on_delete='on_delete.CASCADE', related_name='cpf_cliente', to='reservas.CPF_Cliente')),
                ('reserva_pacote', models.ForeignKey(on_delete='on_delete.CASCADE', related_name='pacote', to='reservas.Pacote')),
            ],
        ),
        migrations.CreateModel(
            name='Uh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_uh', models.CharField(max_length=100)),
                ('valor_uh', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='reserva_uh',
            field=models.ForeignKey(on_delete='on_delete.CASCADE', related_name='uh', to='reservas.Uh'),
        ),
        migrations.AddField(
            model_name='disponibildiade',
            name='disp_pacote',
            field=models.ForeignKey(on_delete='on_delete.CASCADE', related_name='disp_pacote', to='reservas.Pacote'),
        ),
        migrations.AddField(
            model_name='disponibildiade',
            name='uh_disponiveis',
            field=models.ManyToManyField(to='reservas.Uh'),
        ),
    ]
